"""duolingo word table

Revision ID: 313848895d03
Revises: a673dc9f21c7
Create Date: 2018-11-03 20:31:38.739816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313848895d03'
down_revision = 'a673dc9f21c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duolingo_word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=32), nullable=True),
    sa.Column('pronunciation', sa.String(length=32), nullable=True),
    sa.Column('word_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_class_id'], ['word_class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('duolingo_word')
    # ### end Alembic commands ###
